version: '3.4'

services:
  apigateway.query:
    image: ${DOCKER_REGISTRY}apigatewayquery
    build:
      context: .
      dockerfile: APIGateway.Query/Dockerfile
        depends_on:
            - db
    
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "mh.com123!"
            ACCEPT_EULA: "Y"
